config/routes.rb
Web24studios::Application.routes.draw do
  root to: 'static_pages#home'

  match '/services' => 'static_pages#services'
  match '/services/web_application_development'    => 'static_pages#services_web_application_development'
  match '/services/website_design_and_development' => 'static_pages#services_website_design_and_development'
  match '/services/usability_and_user_interface'   => 'static_pages#services_usability_and_user_interface'
  match '/services/quality_assurance_and_testing'  => 'static_pages#services_quality_assurance_and_testing'
  match '/services/maintenance_and_support'        => 'static_pages#services_maintenance_and_support'

  match '/company/overview'              => 'static_pages#company_overview'
  match '/company/business_philosophies' => 'static_pages#company_business_philosophies'
  match '/company/why_us'                => 'static_pages#company_why_us'

  resources :projects
  match '/portfolio' => 'projects#index'

  match '/contact'      => 'static_pages#contact_form'
  match '/contact/info' => 'static_pages#contact_info'

  resources :posts
  match 'blog' => 'posts#index'

  resources :sessions
  get '/admin'    => 'sessions#new'
  get '/log_out'  => 'sessions#destroy'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title, :user_id
  has_one :user

  validates_presence_of :content
  validates_presence_of :title
  validates_presence_of :user_id
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :client, :published, :showcase, :summary, :title, :www

  validates_presence_of :title
  validates_presence_of :client
  validates_presence_of :summary
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :admin, :password, :password_confirmation

  has_many :posts

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, on: :create
  validates_uniqueness_of :email
  validates_presence_of :email
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :admin

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
      flash[:success] = 'Post was successfully created!'
      redirect_to @post
    else
      render 'new'
    end
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      flash[:success] = 'Post was successfully updated!'
      redirect_to @post
    else
      flash[:error] = 'Failed to update Post.'
      render action: :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:success] = "#{@post.title} was successfully deleted."
      redirect_to posts_url
    else
      flash[:error] = 'Failed to delete post.'
      redirect_to @post 
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @showcased_projects = Project.where(showcase: :Y, published: :Y)
    @published_projects = Project.where(showcase: :N, published: :Y)
  end

  def show
    @project = Project.find(params[:id])
    if @project.published != :Y
      redirect_to projects_path
    end
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      flash[:success] = 'Project was successfully created!'
      redirect_to @project
    else
      render :new
    end
  end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(params[:project])
      flash[:success] = 'Project was successfully updated!'
      redirect_to @project
    else
      flash[:error] = 'Failed to update project.'
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      flash[:success] = "#{@project.title} was successfully deleted."
      redirect_to projects_url
    else
      flash[:error] = 'Failed to delete project.'
      redirect_to @project
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      flash[:success] = "Successfully Logged In!"
      redirect_to root_path
   else
     flash[:error] = "Invalid email or password"
     render "new"
   end
 end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logged out."
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def services
  end

  def services_web_application_development
  end

  def services_website_design_and_development
  end

  def services_usability_and_user_interface
  end

  def services_quality_assurance_and_testing
  end

  def services_maintenance_and_support
  end

  def company_business_philosophies
  end

  def company_overview
  end

  def company_why_us
  end

  def contact_form
  end

  def contact_info
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = 'User Successfully created!'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def new
    @user = User.new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per page basis
  def full_title(page_title)
    base_title = 'Web24Studios'
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def get_sidebar(type)
    if type == 'Company'
      links = [ link_to( :Overview, company_overview_path),
                link_to( "Our Business Philosophies", company_business_philosophies_path),
                link_to( "Why Us", company_why_us_path) ]
    elsif type == 'Services'
      links = [ link_to( "Web Application Development", services_web_application_development_path),
                link_to( "Website Design and Development", services_website_design_and_development_path),
                link_to( "Usability and User Interface", services_usability_and_user_interface_path),
                link_to( "Quality Assurance and Testing", services_quality_assurance_and_testing_path),
                link_to( "Maintenance and Support", services_maintenance_and_support_path) ]
    else
      return
    end

    html = "<aside class=\"side-bar side-navigation\"><h3>#{type}</h3><ul>"
    links.each do |link|
      html << "<li>#{link}</li>"
    end
    html << "</ul></aside>"
    return html
  end

  private
  # give the ability to find a sessioned user across the application
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]

    if @current_user.nil?
      false
    else
      @current_user.admin ||= 0   # just a safety precaution
      @current_user
    end
  end

  def current_user_is_admin
    if current_user
      @current_user.admin
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
%footer
  %nav.navbar
    .navbar-inner
      %ul.nav
        %li #{link_to :Blog, posts_path}
      %ul.nav.pull-right
        - if current_user
          %li.non-link #{@current_user.email}
          %li #{link_to 'Log Out', log_out_path}
        - else
          %li #{link_to :Admin, admin_path}

app/views/layouts/_header.html.haml
%header.row
  %h1#logo.span9
    = link_to :Web24Studios, root_path
  .span3
    #search.row
      /= form_tag( '/test', method: :get)
      /.span2
      /  = text_field_tag :query
      /.span1
      /  = submit_tag :Search
  %nav.span12.navbar
    .navbar-inner
      %ul.nav
        %li.dropdown.dropdown-toggle
          = link_to :Company, company_overview_path
        %li.dropdown #{ link_to :Services, services_path }
        %li #{ link_to :Portfolio, portfolio_path }
        %li #{ link_to :Contact, contact_path }

app/views/layouts/_shim.html.haml
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.haml
= raw get_sidebar(yield(:sidebar_type))

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title #{ full_title yield(:title) }
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = render 'layouts/shim'
  %body.container
    = render 'layouts/header'
    #main.row
      #content.row
        -flash.each do |key, value|
          %div{ class: "alert alert-#{key}" }
            = value
        = yield
      = render 'layouts/sidebar'
    = render 'layouts/footer'
    = debug(params) if Rails.env.development?

app/views/posts/_form.html.haml
= form_for(@post, { class: "form form-horizontal span6 offset3" } ) do |f|
  %fieldset
    %legend #{yield(:form_legend}
    - if @post.errors.any?
      #error_explanation
        %h2 #{pluralize(@post.errors.count, "error")} prohibited this post from being saved:
        %ul
          - @post.errors.full_messages.each do |msg|
            %li #{msg}
    .control-group
      .control-label
        = f.label :title
      .controls
        = f.text_field :title
    .control-group
      .control-label
        = f.label :author
      .controls
        = f.select :user_id, User.all.collect {|u| [ "#{u.first_name} #{u.last_name}" , u.id ] }
    .control-group
      .control-label
        = f.label :content
      .controls
        = f.text_area :content
    .form-actions
      = f.submit 'Submit'

app/views/posts/edit.html.haml
= provide :form_legen, "Edit #{@post.title}"
= render 'form'

app/views/posts/index.html.haml
%h1 Blog
- @posts.each do |post|
  .post
    %h2.post-title #{ link_to post.title, post }
    .post-content #{post.content}

- if current_user_is_admin
  = button_to 'Add New Post', new_post_path, { method: :get }

app/views/posts/new.html.haml
= provide :form_legend, "Add New Post"
= render 'form'

app/views/posts/show.html.haml
%h1 #{@post.title}
%p Author: #{@post.user_id}
= @post.content

- if current_user_is_admin
  = button_to 'Edit Post', edit_post_path(@post), { method: :get }
  = button_to 'Delete Post', @post, { method: :delete, data: { confirm: "Delete: #{@post.title}?" } }

app/views/projects/_form.html.haml
= form_for(@project, { class: "form form-horizontal span6 offset3" } ) do |f|
  %fieldset
    %legend #{yield(:form_legend)}
    - if @project.errors.any?
      #error_explanation
        %h2 #{pluralize(@project.errors.count, :error)} prohibited this project from being saved:
        %ul
          - @project.errors.full_messages.each do |msg|
            %li #{msg}
    .control-group
      .control-label
        = f.label :www
      .controls
        = f.text_field :www
    .control-group
      .control-label
        = f.label :title
      .controls
        = f.text_field :title
    .control-group
      .control-label
        = f.label :client
      .controls
        = f.text_field :client
    .control-group
      .control-label
        = f.label :summary
      .controls
        = f.text_area :summary
    .control-group
      .control-label
        = f.label :published
      .controls
        = f.select :published, options_for_select([['Yes', 'Y'], ['No', 'N'] ])
    .control-group
      .control-label
        = f.label :showcase
      .controls
        = f.select :showcase, options_for_select([['Yes', 'Y'], ['No', 'N'] ])
    .form-actions
      = f.submit :Submit

app/views/projects/edit.html.haml
= provide :form_legend, "Edit #{@project.title}"
= render 'form'

= button_to :Portfolio, projects_path, method: :get

app/views/projects/index.html.haml
%h1 Portfolio
.showcase
  - @showcased_projects.each do |showcased_project|
    .project
      / todo add some images here or something for the project
- @published_projects.each do |published_project|
  .project
    %h2 #{link_to published_project.title, published_project}
    = button_to :www, published_project.www, method: :get
    = button_to :summary, published_project, method: :get

- if current_user_is_admin
  = button_to 'Add New Project', new_project_path, method: :get

app/views/projects/new.html.haml
= provide :form_legend, 'Add New Project'
= render 'form'
= button_to :Portfolio, projects_path

app/views/projects/show.html.haml
%h2 #{@project.title}
%p #{@project.client}
%p #{@project.summary}

= link_to :www, @project.www

= button_to 'Portfolio', projects_path, method: :get
- if current_user_is_admin
  = button_to 'Edit Project', edit_project_path(@project), { method: :get }
  = button_to 'Delete Project', @project, { method: :delete, data: { confirm: "Delete: #{@project.title}?" } }

app/views/static_pages/company_business_philosophies.html.haml
= provide :title, 'Company Business Philosophies'
= provide :sidebar_type, :Company
%h1 Business Philosophies

app/views/static_pages/company_overview.html.haml
= provide :title, 'Company Overview'
= provide :sidebar_type, :Company
%h1 Overview

app/views/static_pages/company_why_us.html.haml
= provide :title, 'Why Us'
= provide :sidebar_type, :Company
%h1 Why Us

app/views/static_pages/contact.html.haml
= provide :title, :Contact
%h2 Contact Information

app/views/static_pages/contact_form.html.haml
= provide :title, :Contact
%h1 Contact Form

app/views/static_pages/contact_info.html.haml
= provide :title, 'Contact Info'
%h1 Contact Info

app/views/static_pages/home.html.haml
.span10.offset1
  %h1 Efficient Development. Effective Solutions
  %p.lead We provide quality web solutions to enable your business needs. Built behind a industry standard usability and testing framework Web24Studios delivers an effective solution for every client - no matter the project complexicity.
.span6
  .row
    .span1
      = image_tag 'rails.png'
    .span5
      %h2 #{link_to 'Web Application Development', services_web_application_development_path}
    .span6
      %p Robust applications are the foundation of an effective business model. Web Applications enable the full potential of your market strategy. through precise, high data traffic.
.span6
  .row
    .span1
      = image_tag 'rails.png'
    .span5
      %h2 #{link_to 'Web Design and Development', services_website_design_and_development_path}
    .span6
      %p Visually appealling and a structurally sound coding architecture combine to deliver your exact design or marketing needs.
.span12
  %h2 #{link_to 'Our Recent Work', projects_path}
  .row
    .span3
      = image_tag 'rails.png'
    .span3
      = image_tag 'rails.png'
    .span3
      = image_tag 'rails.png'
.span12
  %h2 #{link_to 'Our Blog', posts_path}
  - Post.find(:all, :order => "created_at desc", :limit => 3).each do |post|
    %p #{post.created_at} - #{link_to post.title, post}

app/views/static_pages/services.html.haml
= provide :title, :Services
= provide :sidebar_type, :Services
%h1 Services

app/views/static_pages/services_maintenance_and_support.html.haml
= provide :title, 'Maintenance and Support'
= provide :sidebar_type, :Services
%h1 Maintenance and Support

app/views/static_pages/services_quality_assurance_and_testing.html.haml
= provide :title, 'Quality Assurance and Testing'
= provide :sidebar_type, :Services
%h1 Quality Assurance and Testing

app/views/static_pages/services_usability_and_user_interface.html.haml
= provide :title, 'Usability and User Interface'
= provide :sidebar_type, :Services
%h2 Usability and User Interface

app/views/static_pages/services_web_application_development.html.haml
= provide :title, 'Web Application Development'
= provide :sidebar_type, :Services
%h2 Web Application Development

app/views/static_pages/services_website_design_and_development.html.haml
= provide :title, 'Website Design and Development'
= provide :sidebar_type, :Services
%h2  Website Design and Development

app/views/static_pages/why_us.html.haml
= provide :title, 'Why Us'
%h2 Why Us